email: "your@email.com"
password: "#y0ur-p4$$w0rd"
imap_server: "imap.mailserver.com"
anthropic_api_key: "your-anthropic_api_key"
openai_api_key: "your-openai_api_key"
openai_model_name: "gpt-4-turbo-preview"  # or "gpt-3.5-turbo"
claude_model_name: "claude-3-opus-20240229"  # or other Claude model versions
max_tokens: 1000
temperature: 0.7
mark_as_read: true
blacklist:
  - "spam@example.com"
  - "newsletter@"
  - "noreply@"
system_prompt: |
  You are an email assistant. Generate helpful and professional responses to emails.
  When responding:
  1. Maintain a professional tone
  2. Address all points in the original email
  3. Be concise but thorough
  4. Sign off appropriately